### ISSUE TITLE
Ticking World Crash

### ISSUE THREAD

**Issue by gmnovakrc** [coolAlias/StructureGenerationAPI#1]
MC 1.7.10
Mowzies Mobs 1.7.10-1.2.99
Not sure if this is more of a Mowzies Mobs issue, seems like it uses this for structure generation. 
But I got this crash out of the blue and I don't have StructureGenAPI installed separately as a mod.

[crash-2021-11-10_12.22.24-server.txt](https://github.com/coolAlias/StructureGenerationAPI/files/7514890/crash-2021-11-10_12.22.24-server.txt)

**Comment by coolAlias** [comment]
This repository is no longer being maintained, sorry.
